platform :ios, '12.0'
use_frameworks!

target 'Templater_Example' do
  pod 'Templater', :path => '../'

  target 'Templater_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
  pod 'Nimble', '~> 8.0'
  end
end
